winogrande:
  num_labels: 2
  report_ttac: [0.7, 0.8, 0.9]
  target_acc: 0.9

sst2:
  num_labels: 2
  report_ttac: [0.7, 0.8, 0.9]
  target_acc: 0.9

arc:
  num_labels: 4
  report_ttac: [0.4, 0.6, 0.7]
  target_acc: 0.7

hellaswag:
  num_labels: 4
  report_ttac: [0.3, 0.5, 0.7]
  target_acc: 0.7

piqa:
  num_labels: 2
  report_ttac: [0.5, 0.7, 0.8]
  target_acc: 0.73

mnli:
  num_labels: 3
  report_ttac: [0.6, 0.7, 0.75]
  target_acc: 0.75

quality:
  num_labels: 4
  report_ttac: [0.3, 0.5, 0.7]
  target_acc: 0.75

hotpotqa:
  report_ttac: [0.1, 0.3, 0.5]
  target_acc: 0.75

squad:
  report_ttac: [0.4, 0.6, 0.8]
  target_acc: 0.8

tinysquad:
  report_ttac: [0.4, 0.5] # thresholds you care about
  target_acc: 40 # interpreted as EM
newsqa:
  report_ttac: [0.3, 0.4]
  target_acc: 30
triviaqa:
  report_ttac: [0.25, 0.35]
  target_acc: 25
